# Generated by Django 3.2.6 on 2021-11-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_patientinfo_staff_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_charge', models.IntegerField()),
                ('room_charge', models.IntegerField(default=350)),
                ('no_of_days', models.IntegerField()),
                ('total', models.FloatField()),
                ('patient_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.patientinfo')),
            ],
        ),
    ]
