# Generated by Django 3.2.6 on 2021-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=455)),
                ('type_treatment', models.CharField(choices=[('hear', 'Hear'), ('ortho', 'Ortho'), ('bodycheckup', 'Bodycheckup')], default='Hear', max_length=11)),
            ],
        ),
    ]
