# Generated by Django 3.2.6 on 2021-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doc_pic',
            field=models.ImageField(default='media/un.jpg', upload_to='media/'),
        ),
    ]
